[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "kennedy-rodrigue-wiki"
authors = [{name = "Ekarin Pongpipat", email = "epongpipat@gmail.com"}]
dynamic = ["version", "description"]
